name: quay.io image

on:
  # manual dispatch
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag.'
        required: true
jobs:
  publish:
    name: Build and push container
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

        # extract metadata for labels https://github.com/crazy-max/ghaction-docker-meta
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: quay.io/wire/broadcast

        # setup docker actions https://github.com/docker/build-push-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # login to Quay repo
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: wire+roman_github_actions
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          tags: quay.io/wire/broadcast:${{ github.event.inputs.tag }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          build-args: |
            release_version=${{ github.event.inputs.tag }}
